// Code generated by generate_routes.go. DO NOT EDIT.
package handler

// Telegram is the interface for interacting with a chat
type Telegram interface {
	SendMessage(text string)
	ChatID() int64
}

// HandlerFunc defines a command handler
type HandlerFunc func(ctx Telegram)

// BotEngine runs the bot
type BotEngine interface {
	Run()
}

var routes = make(map[string]HandlerFunc)

func RegisterRoute(cmd string, handler HandlerFunc) {
	routes[cmd] = handler
}

func GetHandler(cmd string) (HandlerFunc, bool) {
	h, ok := routes[cmd]
	return h, ok
}

func init() {
	RegisterRoute("/start", StartHandler)
	RegisterRoute("/help", HelpHandler)
	RegisterRoute("/info", InfoHandler)
}
